of_source: /media/data/openFrameworks
share_folder: share/
www_dir: tmp/web/
cpu_count: 4
memory_size: 2048

boxes:
  - name: vagrant-windows7-64bit
    distro: 'win'
    pretty_name: 'Windows 7 Professional 64bit'
  - name: vagrant-osx-10.6.2
    distro: 'osx'
    pretty_name: 'Mac OS X 10.6.2'
  - name: vagrant-archlinux-gnome-32bit
    distro: 'archlinux'
    pre_command: 'sudo pacman -Syu --noprogressbar --needed --noconfirm'
    install_scripts:
      - 'install_codecs.sh'
      - 'install_dependencies.sh'
      - 'install_codeblocks.sh'
      - 'remove_codeblocks.sh'
    pretty_name: 'Arch Linux GNOME 32bit'
  - name: 'vagrant-fedora16-gnome-32bit'
    distro: 'fedora' #name of distro folder in of/scripts
    pre_command: 'sudo yum update -y'
    install_scripts:
      - 'install_codecs.sh'
      - 'install_dependencies.sh'
      - 'install_codeblocks.sh'
      - 'remove_codeblocks.sh'
    pretty_name: 'Fedora 16 GNOME 32bit'
  - name: vagrant-ubuntu-12.04-32bit
    distro: 'ubuntu'
    pre_command: 'sudo apt-get update -y && sudo apt-get dist-upgrade -y'
    install_scripts:
      - 'install_codecs.sh'
      - 'install_dependencies.sh'
      - 'install_codeblocks.sh'
      - 'remove_codeblocks.sh'
    pretty_name: 'Ubuntu 12.04 32bit'
  - name: vagrant-debian6.0.5-gnome-32bit
    distro: 'debian'
    pre_command: 'sudo apt-get update -y && sudo apt-get dist-upgrade -y'
    install_scripts:
      - 'install_codecs.sh'
      - 'install_dependencies.sh'
      - 'install_codeblocks.sh'
      - 'remove_codeblocks.sh'
    pretty_name: 'Debian 6.0.5 GNOME 32bit'
  # - name: vagrant-ubuntu-12.04-64bit
  #   distro: 'ubuntu'
  #   pre_command: 'sudo apt-get update -y && sudo apt-get dist-upgrade -y'
  #   install_scripts:
  #     - 'install_codecs.sh'
  #     - 'install_dependencies.sh'
  #     - 'install_codeblocks.sh'
  #     - 'remove_codeblocks.sh'
  #   pretty_name: 'Ubuntu 12.04 GNOME 64bit'
