of_source: /media/ben/data/openFrameworks
vagrant_home: /media/ben/data/vagrant
share_folder: share/
www_dir: tmp/web/
cpu_count: 4
memory_size: 2048
db:
  adapter: sqlite3
  database: db.sqlite3
  pool: 5
  timeout: 5000
